[theme]
primaryColor = "#F97316"              # Tünel turuncusu (Butonlar ve ana vurgular)
backgroundColor = "#0F172A"           # Logodaki tünel içi derin lacivert (Gözü yormayan zemin)
secondaryBackgroundColor = "#1E293B" # Sol menü (Sidebar) ve kart alanları (Derin lacivert)
textColor = "#F8FAFC"                 # Okunaklı açık gri / beyaz yazı
font = "sans serif"

[server]
maxUploadSize = 200

[client]
showErrorDetails = false

[browser]
gatherUsageStats = false